name: "move updated code to server"
on:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: "set ssh keys"
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: "deploy to server"
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
              cd apps
              cd elene-metreveli-epic-movie-quotes-back
              git pull
              composer install
              php artisan cache:clear
              php artisan config:clear
              php artisan optimize
              php artisan migrate
          EOF
